#pragma once

#include "NativeGameplayTags.h"


namespace CosGameTags
{
	CROWNOFSIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Target)
	CROWNOFSIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Target_Ally)
	CROWNOFSIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Target_Hero)
	CROWNOFSIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Target_Minion)
	CROWNOFSIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Target_Enemy)
	
	CROWNOFSIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_CloseRewardScreen)
	CROWNOFSIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Debug_DispathcerHubUpdate);
	
}
